# SaneClip Outreach Configuration

project_name: SaneClip
github_repo: sane-apps/SaneClip
lemon_squeezy_product_id: null  # TBD

# Known non-issues (don't flag these)
known_facts:
  - "Lemon Squeezy bounce emails are normal (test mode)"

# PIRACY ALERT — DMCA takedown needed
piracy:
  - site: "macked.app"
    url: "macked.app/saneclip-mac-crack.html"
    date_found: "2026-02-20"
    status: "needs_dmca"
    notes: "Active crack page for SaneClip found via GitHub bookmark dump."

# Curated listings
launches:
  - platform: "awesome-mac"
    url: "https://github.com/jaywcjlove/awesome-mac/pull/1804"
    date: "2026-02-10"
    status: "merged"
    notes: "99k star repo."
  - platform: "open-source-mac-os-apps"
    date: "2026-02-20"
    status: "merged"
    notes: "47k star repo. PR #1009 merged."
  - platform: "awesome-macOS"
    url: "https://github.com/iCHAIT/awesome-macOS/pull/698"
    date: "2026-02-20"
    status: "submitted"
    notes: "17.8k star repo. PR #698."

# Active launches (check status on each run)
launches: []

# Competitor issues we've already responded to
competitor_responses: []

# Influencer outreach tracking
influencer_outreach:
  sent: []
  considering: []

# Active customer conversations
customer_conversations: []

# Keywords for competitor scanning
competitors:
  - "macpaste"
  - "paste"
  - "clipboard manager"
  - "clipboard history"
  - "macos clipboard"

# X/Twitter search keywords (for outreach skill)
x_search_keywords:
  - "clipboard manager macos"
  - "clipboard history app"
  - "macpaste alternative"
  - "paste app alternative"

# X/Twitter draft templates
x_tweet_drafts:
  - "SaneClip: Privacy-first clipboard manager. Touch ID protected, AES-256 encrypted, 100% on-device. No cloud, no tracking."
  - "Just shipped SaneClip 1.4: Military-grade encryption for your clipboard history. Keychain integration, URL scheme confirmations, HTTPS webhooks."
