disabled_rules:
  - trailing_whitespace
  - todo
  - identifier_name
  - line_length
  - type_body_length
  - function_body_length
  - cyclomatic_complexity
  - nesting
  - shorthand_operator

excluded:
  - build
  - .build
  - DerivedData
  - SourcePackages
  - Pods
  - scripts

file_length:
  warning: 1300
  error: 1500
