name: SaneClip
options:
  bundleIdPrefix: com.saneclip
  deploymentTarget:
    macOS: 15.0
    iOS: 18.0
  xcodeVersion: 16.0

configs:
  Debug: debug
  Release: release
  Release-AppStore: release

packages:
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.6.0

settings:
  DEAD_CODE_STRIPPING: YES
  SWIFT_EMIT_LOC_STRINGS: YES
  ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
  ENABLE_HARDENED_RUNTIME: YES
  GENERATE_INFOPLIST_FILE: YES
  # Recommended warnings
  CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING: YES
  CLANG_WARN_BOOL_CONVERSION: YES
  CLANG_WARN_COMMA: YES
  CLANG_WARN_CONSTANT_CONVERSION: YES
  CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
  CLANG_WARN_EMPTY_BODY: YES
  CLANG_WARN_ENUM_CONVERSION: YES
  CLANG_WARN_INFINITE_RECURSION: YES
  CLANG_WARN_INT_CONVERSION: YES
  CLANG_WARN_NON_LITERAL_NULL_CONVERSION: YES
  CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF: YES
  CLANG_WARN_OBJC_LITERAL_CONVERSION: YES
  CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER: YES
  CLANG_WARN_RANGE_LOOP_ANALYSIS: YES
  CLANG_WARN_STRICT_PROTOTYPES: YES
  CLANG_WARN_SUSPICIOUS_MOVE: YES
  CLANG_WARN_UNREACHABLE_CODE: YES
  CLANG_WARN__DUPLICATE_METHOD_MATCH: YES
  ENABLE_STRICT_OBJC_MSGSEND: YES
  GCC_NO_COMMON_BLOCKS: YES
  GCC_WARN_64_TO_32_BIT_CONVERSION: YES
  GCC_WARN_ABOUT_RETURN_TYPE: YES_ERROR
  GCC_WARN_UNDECLARED_SELECTOR: YES
  GCC_WARN_UNINITIALIZED_AUTOS: YES_AGGRESSIVE
  GCC_WARN_UNUSED_FUNCTION: YES
  GCC_WARN_UNUSED_VARIABLE: YES
  SWIFT_STRICT_CONCURRENCY: complete

schemes:
  SaneClip:
    build:
      targets:
        SaneClip: all
        SaneClipTests: [test]
        SaneClipWidgets: all
    test:
      targets:
        - SaneClipTests
    profile:
      config: Release
    run:
      config: Debug
    archive:
      config: Release

  SaneClipIOS:
    build:
      targets:
        SaneClipIOS: all
        SaneClipIOSWidgets: all
        SaneClipIOSShare: all
    profile:
      config: Release
    run:
      config: Debug
    archive:
      config: Release

targets:
  SaneClip:
    type: application
    platform: macOS
    bundleId: com.saneclip.app
    deploymentTarget:
      macOS: 15.0
    sources:
      - main.swift
      - SaneClipApp.swift
      - path: Core
        excludes:
          - "**/CLAUDE.md"
      - path: UI
        excludes:
          - "**/CLAUDE.md"
      - path: Shared
        excludes:
          - "**/CLAUDE.md"
      - path: ../../infra/SaneProcess/shared/MoveToApplications.swift
      - Resources
    dependencies:
      - package: KeyboardShortcuts
      - package: Sparkle
      - target: SaneClipWidgets
        embed: true
        codeSign: true
    info:
      path: SaneClip/Info.plist
      properties:
        LSUIElement: true
        LSApplicationCategoryType: "public.app-category.productivity"
        NSAppleEventsUsageDescription: "SaneClip needs to paste clipboard content to other applications."
        # URL Scheme (Phase 3)
        CFBundleURLTypes:
          - CFBundleURLName: "SaneClip URL Scheme"
            CFBundleURLSchemes:
              - saneclip
        # Sparkle Auto-Update Configuration (CRITICAL - was missing!)
        SUFeedURL: "https://saneclip.com/appcast.xml"
        SUPublicEDKey: "7Pl/8cwfb2vm4Dm65AByslkMCScLJ9tbGlwGGx81qYU="
        SUEnableAutomaticChecks: true
        SUEnableSystemProfiling: false
    settings:
      base:
        PRODUCT_NAME: SaneClip
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
        MARKETING_VERSION: "2.0"
        CURRENT_PROJECT_VERSION: "7"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 6.0
        MACOSX_DEPLOYMENT_TARGET: 15.0
        ARCHS: arm64
        VALID_ARCHS: arm64
        CODE_SIGN_STYLE: Manual
        CODE_SIGN_INJECT_BASE_ENTITLEMENTS: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClipDebug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClip.entitlements
          PROVISIONING_PROFILE_SPECIFIER: "SaneClip Developer ID"
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_ENTITLEMENTS: SaneClip/SaneClipAppStore.entitlements
          OTHER_SWIFT_FLAGS: "-D APP_STORE -D ENABLE_SYNC"
    postCompileScripts:
      - script: |
          if which swiftlint >/dev/null; then
            swiftlint . 2>&1 | sed 's/: error:/: warning:/' || true
          else
            echo "warning: SwiftLint not installed"
          fi
        name: Run SwiftLint
        basedOnDependencyAnalysis: false
    postBuildScripts:
      - script: |
          if [ "$CONFIGURATION" == "Release-AppStore" ]; then
            echo "App Store build: stripping Sparkle framework and keys..."
            # Remove Sparkle framework from app bundle
            rm -rf "${BUILT_PRODUCTS_DIR}/${FRAMEWORKS_FOLDER_PATH}/Sparkle.framework"
            # Strip Sparkle keys from built Info.plist
            /usr/libexec/PlistBuddy -c "Delete :SUFeedURL" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Delete :SUPublicEDKey" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Delete :SUEnableAutomaticChecks" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}" 2>/dev/null || true
            /usr/libexec/PlistBuddy -c "Delete :SUEnableSystemProfiling" "${BUILT_PRODUCTS_DIR}/${INFOPLIST_PATH}" 2>/dev/null || true
            echo "App Store build: Sparkle fully removed"
          fi
        name: Strip Sparkle for App Store
        basedOnDependencyAnalysis: false

  SaneClipTests:
    type: bundle.unit-test
    platform: macOS
    bundleId: com.saneclip.appTests
    deploymentTarget:
      macOS: 15.0
    testTarget: SaneClip
    sources:
      - Tests
    dependencies:
      - target: SaneClip
    settings:
      base:
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          CODE_SIGN_IDENTITY: "-"
        Release:
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Apple Development"

  SaneClipWidgets:
    type: app-extension
    platform: macOS
    bundleId: com.saneclip.app.widgets
    deploymentTarget:
      macOS: 15.0
    sources:
      - Widgets
      - path: Core/Models/WidgetClipboardItem.swift
    info:
      path: Widgets/Info.plist
      properties:
        CFBundleDisplayName: SaneClip Widgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_NAME: SaneClipWidgets
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.widgets
        MARKETING_VERSION: "2.0"
        CURRENT_PROJECT_VERSION: "7"
        SWIFT_VERSION: 6.0
        CODE_SIGN_STYLE: Manual
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks @executable_path/../../../../Frameworks"
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev.widgets
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: Widgets/SaneClipWidgetsDebug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.widgets
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Developer ID Application"
          CODE_SIGN_ENTITLEMENTS: Widgets/SaneClipWidgets.entitlements
          PROVISIONING_PROFILE_SPECIFIER: "SaneClip Widgets Developer ID"
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.widgets
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_IDENTITY: "Apple Development"
          CODE_SIGN_ENTITLEMENTS: Widgets/SaneClipWidgets.entitlements

  # iOS App
  SaneClipIOS:
    type: application
    platform: iOS
    bundleId: com.saneclip.app
    deploymentTarget:
      iOS: 18.0
    sources:
      - path: iOS
        excludes:
          - "**/CLAUDE.md"
      - path: Shared
        excludes:
          - "**/CLAUDE.md"
      - path: Core/Models/WidgetClipboardItem.swift
      - path: Core/BrandColors.swift
      - path: Core/Sync
        excludes:
          - "**/CLAUDE.md"
      - path: Core/Security/KeychainHelper.swift
      - path: Core/Security/HistoryEncryption.swift
    dependencies:
      - target: SaneClipIOSWidgets
        embed: true
        codeSign: true
      - target: SaneClipIOSShare
        embed: true
        codeSign: true
    info:
      path: iOS/Info.plist
      properties:
        CFBundleDisplayName: SaneClip
        LSApplicationCategoryType: "public.app-category.productivity"
        ITSAppUsesNonExemptEncryption: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_NAME: SaneClip
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ENABLE_PREVIEWS: YES
        SWIFT_VERSION: 6.0
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Manual
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: iOS/SaneClipIOSDebug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: iOS/SaneClipIOS.entitlements
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_ENTITLEMENTS: iOS/SaneClipIOS.entitlements
          OTHER_SWIFT_FLAGS: "-D APP_STORE -D ENABLE_SYNC"

  # iOS Widgets
  SaneClipIOSWidgets:
    type: app-extension
    platform: iOS
    bundleId: com.saneclip.app.ioswidgets
    deploymentTarget:
      iOS: 18.0
    sources:
      - iOSWidgets
      - path: Core/Models/WidgetClipboardItem.swift
    info:
      path: iOSWidgets/Info.plist
      properties:
        CFBundleDisplayName: SaneClip Widgets
        NSExtension:
          NSExtensionPointIdentifier: com.apple.widgetkit-extension
    settings:
      base:
        PRODUCT_NAME: SaneClipIOSWidgets
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.ioswidgets
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: 6.0
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Manual
        SKIP_INSTALL: YES
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev.ioswidgets
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: iOSWidgets/SaneClipIOSWidgetsDebug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.ioswidgets
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: iOSWidgets/SaneClipIOSWidgets.entitlements
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.ioswidgets
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_ENTITLEMENTS: iOSWidgets/SaneClipIOSWidgets.entitlements

  # iOS Share Extension
  SaneClipIOSShare:
    type: app-extension
    platform: iOS
    bundleId: com.saneclip.app.share
    deploymentTarget:
      iOS: 18.0
    sources:
      - iOSShareExtension
      - path: Core/Models/WidgetClipboardItem.swift
    info:
      path: iOSShareExtension/Info.plist
      properties:
        CFBundleDisplayName: Save to SaneClip
        NSExtension:
          NSExtensionPointIdentifier: com.apple.share-services
          NSExtensionPrincipalClass: "$(PRODUCT_MODULE_NAME).ShareViewController"
          NSExtensionAttributes:
            NSExtensionActivationRule:
              NSExtensionActivationSupportsText: true
              NSExtensionActivationSupportsWebURLWithMaxCount: 1
              NSExtensionActivationSupportsWebPageWithMaxCount: 1
    settings:
      base:
        PRODUCT_NAME: SaneClipIOSShare
        PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.share
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: 6.0
        IPHONEOS_DEPLOYMENT_TARGET: 18.0
        TARGETED_DEVICE_FAMILY: "1,2"
        CODE_SIGN_STYLE: Manual
        SKIP_INSTALL: YES
        LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks @executable_path/../../../../Frameworks"
      configs:
        Debug:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.dev.share
          CODE_SIGN_IDENTITY: "-"
          CODE_SIGN_ENTITLEMENTS: iOSShareExtension/SaneClipShareDebug.entitlements
        Release:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.share
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_IDENTITY: "Apple Distribution"
          CODE_SIGN_ENTITLEMENTS: iOSShareExtension/SaneClipShare.entitlements
        Release-AppStore:
          PRODUCT_BUNDLE_IDENTIFIER: com.saneclip.app.share
          DEVELOPMENT_TEAM: M78L6FXD48
          CODE_SIGN_STYLE: Automatic
          CODE_SIGN_ENTITLEMENTS: iOSShareExtension/SaneClipShare.entitlements
