import AppKit
@preconcurrency import ApplicationServices
import Combine
import os.log
import SaneUI
import SwiftUI
import UniformTypeIdentifiers
#if APP_STORE
    import UserNotifications
#endif
import WidgetKit

@MainActor
@Observable
// swiftlint:disable:next type_body_length
class ClipboardManager {
    static var shared: ClipboardManager!

    nonisolated static let accessibilityAlertTitle = "Auto-Paste Needs Access"
    nonisolated static let accessibilityAlertMessage = "Clip copied. Enable Accessibility for one-key paste.\nAlready enabled? Quit and reopen."
    nonisolated static let accessibilityOpenButtonTitle = "Open Access"
    nonisolated static let accessibilityRetryButtonTitle = "Retry"
    nonisolated static let accessibilityManualButtonTitle = "Manual"

    /// Free tier history cap — Pro users get unlimited.
    nonisolated static let freeHistoryCap = 50
    nonisolated static func historyLimit(maxHistorySize: Int, isPro: Bool) -> Int {
        if isPro {
            return maxHistorySize
        }
        return min(maxHistorySize, freeHistoryCap)
    }

    var history: [ClipboardItem] = []
    var pinnedItems: [ClipboardItem] = []
    var pasteStack: [ClipboardItem] = []
    var isPasteStackMode: Bool { !pasteStack.isEmpty }
    private var lastChangeCount: Int = 0

    /// License service for Pro feature gating.
    var licenseService: LicenseService? {
        didSet {
            enforceHistoryLimitIfNeeded()
        }
    }
    /// Tracks the pasteboard changeCount at which our last self-write completed.
    /// checkClipboard() skips processing while changeCount hasn't advanced past this value.
    /// This is more robust than a simple boolean because it handles the dual changeCount
    /// increment from clearContents()+setString() and survives timing edge cases.
    private var selfWriteChangeCount: Int = 0
    /// Backward-compatible accessor for external callers (e.g. URLSchemeHandler).
    /// Setting to true snapshots a high changeCount; setting to false clears suppression.
    var isSelfWrite: Bool {
        get { selfWriteChangeCount > 0 }
        set { selfWriteChangeCount = newValue ? Int.max : 0 }
    }

    /// Whether a paste operation is currently in flight (prevents overlapping Cmd+V simulations)
    private var isPasting = false
    private var suppressPermissionPromptUntil: Date?
    private let permissionPromptCooldown: TimeInterval = 120
    private var lastClipboardContent: String?
    private var lastCopyTime: Date?
    private var timer: Timer?
    private var ignoreNextCapture = false
    private var capturePausedUntil: Date?
    private var maxHistorySize: Int { SettingsModel.shared.maxHistorySize }
    private let logger = Logger(subsystem: "com.saneclip.app", category: "ClipboardManager")

    var isCapturePaused: Bool {
        guard let capturePausedUntil else { return false }
        if Date() >= capturePausedUntil {
            self.capturePausedUntil = nil
            return false
        }
        return true
    }

    var capturePauseRemainingText: String? {
        guard isCapturePaused, let capturePausedUntil else { return nil }
        let remaining = max(0, Int(capturePausedUntil.timeIntervalSinceNow))
        let minutes = remaining / 60
        let seconds = remaining % 60
        if minutes > 0 {
            return "\(minutes)m \(seconds)s"
        }
        return "\(seconds)s"
    }

    // Security: Types to ignore — only ConcealedType (passwords/secrets) and
    // AutoGeneratedType (generated passwords). TransientType is intentionally NOT
    // included because many non-password apps set it alongside legitimate content
    // (e.g. browser image copies), and the ignoredBundleIDs check already catches
    // actual password managers.
    private let ignoredTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType")
    ]

    // Security: Bundle IDs to ignore (password managers)
    private let ignoredBundleIDs: Set<String> = [
        "com.agilebits.onepassword",
        "com.dashlane.dashlane",
        "com.lastpass.lastpass",
        "com.wsigenesis.1Password7"
    ]

    init() {
        lastChangeCount = NSPasteboard.general.changeCount
        startMonitoring()
        loadHistory()
    }

    private func startMonitoring() {
        timer = Timer.scheduledTimer(withTimeInterval: 0.25, repeats: true) { [weak self] _ in
            Task { @MainActor in
                self?.checkClipboard()
            }
        }
    }

    private func checkClipboard() {
        // Keep history aligned with current tier limits (covers downgrade/migration states).
        enforceHistoryLimitIfNeeded()

        // Cleanup expired items periodically
        cleanupExpiredItems()

        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        // Skip if we just wrote to the pasteboard ourselves (paste-as-transform, snippets, etc.)
        // Uses changeCount tracking: suppresses until pasteboard advances past our write.
        if selfWriteChangeCount > 0 {
            let swc = selfWriteChangeCount
            let cc = pasteboard.changeCount
            if cc <= swc {
                logger.info("Self-write suppressed: changeCount \(cc) <= selfWrite \(swc)")
                return
            }
            logger.info("Self-write cleared: changeCount \(cc) > selfWrite \(swc)")
            selfWriteChangeCount = 0
        }

        if isCapturePaused {
            logger.debug("Capture paused, skipping clipboard update")
            return
        }

        if ignoreNextCapture {
            ignoreNextCapture = false
            logger.info("Ignored one clipboard change by user request")
            return
        }

        // Security checks
        guard !containsTransientTypes(pasteboard) else { return }

        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let sourceAppBundleID = frontmostApp?.bundleIdentifier
        let sourceAppName = frontmostApp?.localizedName

        guard !isExcludedApp(bundleID: sourceAppBundleID, name: sourceAppName) else { return }
        // Process content
        processClipboardContent(pasteboard, sourceAppBundleID: sourceAppBundleID, sourceAppName: sourceAppName)
    }

    private func containsTransientTypes(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }

        // Log TransientType for monitoring (no longer blocked, but worth tracking)
        if types.contains(NSPasteboard.PasteboardType("org.nspasteboard.TransientType")) {
            let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier ?? "unknown"
            logger.debug("TransientType seen from \(source) (allowed through)")
        }

        for ignored in ignoredTypes where types.contains(ignored) {
            logger.debug("Ignored concealed/auto-generated clipboard content")
            return true
        }
        return false
    }

    private func cleanupExpiredItems() {
        let expireHours = SettingsModel.shared.autoExpireHours
        guard expireHours > 0 else { return }

        let cutoff = Date().addingTimeInterval(-Double(expireHours * 3600))
        let beforeCount = history.count

        // Remove expired items, but preserve pinned items
        history.removeAll { item in
            let shouldRemove = !isPinned(item) && item.timestamp < cutoff
            if shouldRemove, case .image = item.content {
                deleteThumbnail(id: item.id)
            }
            return shouldRemove
        }

        let afterCount = history.count
        if afterCount < beforeCount {
            saveHistory()
            logger.debug("Cleaned up \(beforeCount - afterCount) expired items")
        }
    }

    private func isExcludedApp(bundleID: String?, name: String?) -> Bool {
        guard let bundleID else { return false }

        if SettingsModel.shared.isAppExcluded(bundleID) {
            logger.debug("Skipping clipboard from excluded app: \(name ?? "unknown")")
            return true
        }

        if SettingsModel.shared.protectPasswords, ignoredBundleIDs.contains(bundleID) {
            logger.debug("Skipping clipboard from known password manager: \(bundleID)")
            return true
        }

        return false
    }

    /// Image file extensions for detecting image files copied from Finder
    private static let imageExtensions: Set<String> = [
        "png", "jpg", "jpeg", "gif", "bmp", "tiff", "tif", "webp", "heic", "heif", "ico", "svg"
    ]

    /// Spreadsheet sources that often publish both image and text clipboard representations.
    /// For these apps, text is usually the expected default when a cell range is copied.
    private static let spreadsheetBundleIDs: Set<String> = [
        "com.microsoft.Excel",
        "com.apple.iWork.Numbers"
    ]

    private static let tabularTextTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("public.tab-separated-values-text"),
        NSPasteboard.PasteboardType("public.utf8-tab-separated-values-text"),
        NSPasteboard.PasteboardType("public.comma-separated-values-text")
    ]

    private static let plainTextTypes: [NSPasteboard.PasteboardType] = [
        .string,
        NSPasteboard.PasteboardType("public.utf8-plain-text"),
        NSPasteboard.PasteboardType("public.utf16-plain-text"),
        NSPasteboard.PasteboardType("public.plain-text")
    ]

    private static let htmlTypes: [NSPasteboard.PasteboardType] = [
        .html,
        NSPasteboard.PasteboardType("NSHTMLPboardType")
    ]

    private static let rtfTypes: [NSPasteboard.PasteboardType] = [
        .rtf,
        NSPasteboard.PasteboardType("NSRTFPboardType")
    ]

    private static func normalizedNonEmptyText(_ raw: String?) -> String? {
        guard let raw else { return nil }
        let normalized = raw
            .replacingOccurrences(of: "\r\n", with: "\n")
            .replacingOccurrences(of: "\r", with: "\n")
        return normalized.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty ? nil : normalized
    }

    private static func decodeStringData(_ data: Data?) -> String? {
        guard let data else { return nil }
        let encodings: [String.Encoding] = [
            .utf8,
            .utf16,
            .utf16LittleEndian,
            .utf16BigEndian,
            .unicode
        ]
        for encoding in encodings {
            if let decoded = String(data: data, encoding: encoding),
               let normalized = normalizedNonEmptyText(decoded) {
                return normalized
            }
        }
        return nil
    }

    private static func plainText(from item: NSPasteboardItem, preferredTypes: [NSPasteboard.PasteboardType]) -> String? {
        for type in preferredTypes {
            if let text = normalizedNonEmptyText(item.string(forType: type)) {
                return text
            }
            if let decoded = decodeStringData(item.data(forType: type)) {
                return decoded
            }
        }

        guard let conformanceType = item.availableType(from: preferredTypes) else { return nil }
        if let text = normalizedNonEmptyText(item.string(forType: conformanceType)) {
            return text
        }
        return decodeStringData(item.data(forType: conformanceType))
    }

    private static func richText(from item: NSPasteboardItem) -> String? {
        for rtfType in rtfTypes {
            if let rtfData = item.data(forType: rtfType),
               let attributed = try? NSAttributedString(
                   data: rtfData,
                   options: [.documentType: NSAttributedString.DocumentType.rtf],
                   documentAttributes: nil
               ),
               let normalized = normalizedNonEmptyText(attributed.string) {
                return normalized
            }
        }

        for htmlType in htmlTypes {
            if let htmlData = item.data(forType: htmlType),
               let attributed = try? NSAttributedString(
                   data: htmlData,
                   options: [
                       .documentType: NSAttributedString.DocumentType.html,
                       .characterEncoding: String.Encoding.utf8.rawValue
                   ],
                   documentAttributes: nil
               ),
               let normalized = normalizedNonEmptyText(attributed.string) {
                return normalized
            }
        }

        return nil
    }

    private static func htmlString(from item: NSPasteboardItem) -> String? {
        for htmlType in htmlTypes {
            if let decoded = decodeStringData(item.data(forType: htmlType)) {
                return decoded
            }
        }
        return nil
    }

    private static func tabularTextFromHTML(_ html: String) -> String? {
        let lower = html.lowercased()
        let looksTabular = lower.contains("<table") ||
            ((lower.contains("<tr") || lower.contains("<tbody")) &&
                (lower.contains("<td") || lower.contains("<th")))
        guard looksTabular else { return nil }

        guard let rowRegex = try? NSRegularExpression(pattern: #"(?is)<tr\b[^>]*>(.*?)</tr>"#),
              let cellRegex = try? NSRegularExpression(pattern: #"(?is)<t[dh]\b[^>]*>(.*?)</t[dh]>"#)
        else { return nil }

        let htmlRange = NSRange(location: 0, length: html.utf16.count)
        let rowMatches = rowRegex.matches(in: html, options: [], range: htmlRange)
        guard !rowMatches.isEmpty else { return nil }

        var lines: [String] = []
        for rowMatch in rowMatches {
            guard rowMatch.numberOfRanges > 1,
                  let rowRange = Range(rowMatch.range(at: 1), in: html)
            else { continue }
            let rowHTML = String(html[rowRange])
            let rowNSRange = NSRange(location: 0, length: rowHTML.utf16.count)
            let cellMatches = cellRegex.matches(in: rowHTML, options: [], range: rowNSRange)

            let rowCells = cellMatches.compactMap { match -> String? in
                guard match.numberOfRanges > 1,
                      let cellRange = Range(match.range(at: 1), in: rowHTML)
                else { return nil }
                return normalizedNonEmptyText(richText(fromHTMLFragment: String(rowHTML[cellRange])))
            }
            .filter { !$0.isEmpty }

            if !rowCells.isEmpty {
                lines.append(rowCells.joined(separator: "\t"))
            }
        }

        let result = lines.joined(separator: "\n")
        guard result.contains("\t") || result.contains("\n") else { return nil }
        return normalizedNonEmptyText(result)
    }

    private static func richText(fromHTMLFragment fragment: String) -> String {
        let wrapped = "<span>\(fragment)</span>"
        guard let data = wrapped.data(using: .utf8),
              let attributed = try? NSAttributedString(
                  data: data,
                  options: [
                      .documentType: NSAttributedString.DocumentType.html,
                      .characterEncoding: String.Encoding.utf8.rawValue
                  ],
                  documentAttributes: nil
              )
        else {
            return fragment
        }
        return attributed.string
    }

    private static func firstTabularHTMLText(from items: [NSPasteboardItem]) -> String? {
        for item in items {
            guard let html = htmlString(from: item),
                  let tabular = tabularTextFromHTML(html)
            else { continue }
            return tabular
        }
        return nil
    }

    private static func firstPlainText(
        from items: [NSPasteboardItem],
        preferredTypes: [NSPasteboard.PasteboardType]
    ) -> String? {
        for item in items {
            if let text = plainText(from: item, preferredTypes: preferredTypes) {
                return text
            }
        }
        return nil
    }

    /// Internal helper used by capture flow and regression tests.
    static func preferredTextForCapture(
        from pasteboardItems: [NSPasteboardItem],
        sourceAppBundleID: String?
    ) -> String? {
        guard !pasteboardItems.isEmpty else { return nil }

        if let tabularText = firstPlainText(from: pasteboardItems, preferredTypes: tabularTextTypes) {
            return tabularText
        }

        if let htmlTabularText = firstTabularHTMLText(from: pasteboardItems) {
            return htmlTabularText
        }

        let multiItemTexts = pasteboardItems.compactMap { plainText(from: $0, preferredTypes: plainTextTypes) }
        if multiItemTexts.count > 1 {
            return normalizedNonEmptyText(multiItemTexts.joined(separator: "\n"))
        }

        if let singleText = multiItemTexts.first,
           singleText.contains("\t") || singleText.contains("\n") {
            return singleText
        }

        if let sourceAppBundleID,
           spreadsheetBundleIDs.contains(sourceAppBundleID),
           let spreadsheetText = firstPlainText(from: pasteboardItems, preferredTypes: plainTextTypes) {
            return spreadsheetText
        }

        return nil
    }

    private static func bestEffortText(from pasteboard: NSPasteboard) -> String? {
        for type in plainTextTypes {
            if let text = normalizedNonEmptyText(pasteboard.string(forType: type)) {
                return text
            }
            if let decoded = decodeStringData(pasteboard.data(forType: type)) {
                return decoded
            }
        }

        guard let items = pasteboard.pasteboardItems else { return nil }
        if let plainFromItems = firstPlainText(from: items, preferredTypes: plainTextTypes) {
            return plainFromItems
        }

        for item in items {
            if let rich = richText(from: item) {
                return rich
            }
        }

        return nil
    }

    private func addTextClipboardItem(
        _ text: String,
        sourceAppBundleID: String?,
        sourceAppName: String?
    ) {
        if !isTextWithinCaptureLimit(text) {
            logger.info("Skipped oversized text clipboard entry (\(text.utf8.count) bytes)")
            return
        }

        let processedString = processString(text)
        if !isTextWithinCaptureLimit(processedString) {
            logger.info("Skipped oversized processed clipboard entry (\(processedString.utf8.count) bytes)")
            return
        }
        lastClipboardContent = processedString
        lastCopyTime = Date()
        addItem(ClipboardItem(
            content: .text(processedString),
            sourceAppBundleID: sourceAppBundleID,
            sourceAppName: sourceAppName
        ))
    }

    private func processClipboardContent(
        _ pasteboard: NSPasteboard, sourceAppBundleID: String?, sourceAppName: String?
    ) {
        // Check if this is a file copy from Finder — Finder puts the file ICON as TIFF
        // on the pasteboard, not the actual file content. Detect file URLs and load the
        // real image if it's an image file.
        if let fileURL = pasteboard.string(forType: .fileURL).flatMap({ URL(string: $0) }),
           fileURL.isFileURL,
           FileManager.default.fileExists(atPath: fileURL.path) {
            let ext = fileURL.pathExtension.lowercased()
            if Self.imageExtensions.contains(ext) {
                let fileSize = (try? FileManager.default.attributesOfItem(atPath: fileURL.path)[.size] as? Int) ?? 0
                if !isImageDataWithinCaptureLimit(fileSize) {
                    logger.warning("Skipping oversized image file (\(fileSize / 1_000_000)MB): \(fileURL.lastPathComponent)")
                } else if let image = NSImage(contentsOf: fileURL) {
                    let size = image.size
                    logger.debug("Captured image file: \(fileURL.lastPathComponent) \(Int(size.width))×\(Int(size.height))")
                    lastClipboardContent = nil
                    lastCopyTime = nil
                    addItem(ClipboardItem(
                        content: .image(image),
                        sourceAppBundleID: sourceAppBundleID,
                        sourceAppName: sourceAppName
                    ))
                    return
                } else {
                    logger.warning("Failed to load image from file: \(fileURL.lastPathComponent)")
                }
                // Fall through to capture file path as text if image load failed
            }
            // Non-image file: fall through to capture file path as text
        }

        if let pasteboardItems = pasteboard.pasteboardItems,
           let preferredText = Self.preferredTextForCapture(
               from: pasteboardItems,
               sourceAppBundleID: sourceAppBundleID
           ) {
            addTextClipboardItem(
                preferredText,
                sourceAppBundleID: sourceAppBundleID,
                sourceAppName: sourceAppName
            )
            return
        }

        // Check for image data on pasteboard (e.g. "Copy Image" in browser)
        let hasImageType = pasteboard.types?.contains(where: {
            [.tiff, .png].contains($0)
        }) ?? false
        let isSpreadsheetSource = sourceAppBundleID.map { Self.spreadsheetBundleIDs.contains($0) } ?? false

        // Only use pasteboard image if there's no file URL (avoids capturing Finder icons)
        let hasFileURL = pasteboard.types?.contains(.fileURL) ?? false
        if hasImageType, !hasFileURL, let image = NSImage(pasteboard: pasteboard) {
            let imageBytes = image.tiffRepresentation?.count ?? 0
            if !isImageDataWithinCaptureLimit(imageBytes) {
                logger.warning("Skipping oversized image pasteboard item (\(imageBytes / 1_000_000)MB)")
                return
            }
            if isSpreadsheetSource {
                let typesSummary = pasteboard.types?.map(\.rawValue).joined(separator: ", ") ?? "unknown"
                logger.info("Spreadsheet clipboard fell back to image capture. Types: \(typesSummary)")
            }
            let size = image.size
            logger.debug("Captured image: \(Int(size.width))×\(Int(size.height))")
            lastClipboardContent = nil
            lastCopyTime = nil
            addItem(ClipboardItem(
                content: .image(image),
                sourceAppBundleID: sourceAppBundleID,
                sourceAppName: sourceAppName
            ))
        } else if let text = Self.bestEffortText(from: pasteboard) {
            addTextClipboardItem(
                text,
                sourceAppBundleID: sourceAppBundleID,
                sourceAppName: sourceAppName
            )
        } else {
            if isSpreadsheetSource {
                let typesSummary = pasteboard.types?.map(\.rawValue).joined(separator: ", ") ?? "unknown"
                logger.warning("Spreadsheet clipboard had no capturable text/image. Types: \(typesSummary)")
            }
            lastClipboardContent = nil
            lastCopyTime = nil
        }
    }

    private func isTextWithinCaptureLimit(_ text: String) -> Bool {
        let limit = SettingsModel.shared.maxCaptureTextBytes
        guard limit > 0 else { return true }
        return text.utf8.count <= limit
    }

    private func isImageDataWithinCaptureLimit(_ bytes: Int) -> Bool {
        let limit = SettingsModel.shared.maxCaptureImageBytes
        guard limit > 0 else { return true }
        return bytes <= limit
    }

    func ignoreNextCopy() {
        ignoreNextCapture = true
    }

    func pauseCapture(minutes: Int) {
        guard minutes > 0 else {
            capturePausedUntil = nil
            return
        }
        capturePausedUntil = Date().addingTimeInterval(TimeInterval(minutes * 60))
    }

    func resumeCapture() {
        capturePausedUntil = nil
    }

    private func processString(_ string: String) -> String {
        guard licenseService?.isPro == true else {
            return string
        }
        let processed = ClipboardRulesManager.shared.process(string)
        if processed != string {
            logger.debug("Applied clipboard rules to content")
        }
        return processed
    }

    private func addItem(_ item: ClipboardItem) {
        // Don't add duplicates at the top
        if let first = history.first, first.contentHash == item.contentHash {
            return
        }

        // Remove existing duplicate if present
        history.removeAll { $0.contentHash == item.contentHash }

        // Add to front
        history.insert(item, at: 0)

        // Trim to current tier limit, cleaning up thumbnails for removed items.
        enforceHistoryLimitIfNeeded(saveAfterTrim: false)
        saveHistory()

        #if ENABLE_SYNC
            // Queue the new item for iCloud sync
            let shared = SharedClipboardItem(
                id: item.id,
                content: item.sharedContent,
                timestamp: item.timestamp,
                sourceAppBundleID: item.sourceAppBundleID,
                sourceAppName: item.sourceAppName,
                pasteCount: item.pasteCount,
                note: item.note
            )
            SyncCoordinator.shared.queueItemForSync(shared)
        #endif

        let currentCount = history.count
        logger.debug("Added clipboard item, history count: \(currentCount)")
    }

    func paste(item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch item.content {
        case let .text(string):
            pasteboard.setString(string, forType: .string)
        case let .image(image):
            if let tiffData = image.tiffRepresentation {
                pasteboard.setData(tiffData, forType: .tiff)
            }
        }
        selfWriteChangeCount = pasteboard.changeCount

        // Move to front and increment paste count
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            var updatedItem = history.remove(at: index)
            updatedItem.pasteCount += 1
            history.insert(updatedItem, at: 0)
            saveHistory()
        }

        SettingsModel.shared.pasteSound.play()
        dismissAndPaste()
    }

    /// Paste most recent item as plain text (for global shortcut)
    func pasteAsPlainText() {
        guard let item = history.first else { return }
        pasteAsPlainText(item: item)
    }

    /// Paste item as plain text (strips formatting) — Pro only
    func pasteAsPlainText(item: ClipboardItem) {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.plainTextPaste, licenseService: ls)
            }
            return
        }
        guard case let .text(string) = item.content else { return }

        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(string, forType: .string)
        selfWriteChangeCount = pasteboard.changeCount

        // Move to front and increment paste count
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            var updatedItem = history.remove(at: index)
            updatedItem.pasteCount += 1
            history.insert(updatedItem, at: 0)
            saveHistory()
        }

        SettingsModel.shared.pasteSound.play()
        dismissAndPaste()
    }

    /// Smart paste: auto-selects paste behavior based on content type — Pro only
    /// - Code → plain text (preserves indentation, strips rich formatting)
    /// - URL → cleaned URL with tracking params stripped
    /// - Everything else → standard paste
    func pasteSmartMode(item: ClipboardItem) {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.smartPaste, licenseService: ls)
            }
            return
        }
        if item.isCode {
            pasteAsPlainText(item: item)
        } else if item.isURL, case let .text(urlString) = item.content {
            let cleaned = ClipboardItem.stripTrackingParams(from: urlString)
            let pasteboard = NSPasteboard.general
            pasteboard.clearContents()
            pasteboard.setString(cleaned, forType: .string)
            selfWriteChangeCount = pasteboard.changeCount

            if let index = history.firstIndex(where: { $0.id == item.id }) {
                var updatedItem = history.remove(at: index)
                updatedItem.pasteCount += 1
                history.insert(updatedItem, at: 0)
                saveHistory()
            }

            SettingsModel.shared.pasteSound.play()
            dismissAndPaste()
        } else {
            paste(item: item)
        }
    }

    /// Paste using the user's default paste mode preference
    func pasteWithDefaultMode(item: ClipboardItem) {
        guard licenseService?.isPro == true else {
            paste(item: item)
            return
        }
        switch SettingsModel.shared.defaultPasteMode {
        case .standard:
            paste(item: item)
        case .plain:
            pasteAsPlainText(item: item)
        case .smart:
            pasteSmartMode(item: item)
        }
    }

    /// Paste item with a text transformation applied — Pro only
    func pasteWithTransform(item: ClipboardItem, transform: TextTransform) {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.textTransforms, licenseService: ls)
            }
            return
        }
        guard case let .text(string) = item.content else { return }

        let transformed = transform.apply(to: string)
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(transformed, forType: .string)
        selfWriteChangeCount = pasteboard.changeCount
        let swcT = selfWriteChangeCount
        logger.info("pasteWithTransform: \(transform.rawValue), selfWriteChangeCount=\(swcT)")

        // Move to front and increment paste count
        if let index = history.firstIndex(where: { $0.id == item.id }) {
            var updatedItem = history.remove(at: index)
            updatedItem.pasteCount += 1
            history.insert(updatedItem, at: 0)
            saveHistory()
        }

        SettingsModel.shared.pasteSound.play()
        dismissAndPaste()
    }

    /// Paste an expanded snippet to the active application — Pro only
    func pasteSnippet(_ snippet: Snippet, values: [String: String] = [:]) {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.snippets, licenseService: ls)
            }
            return
        }
        let expanded = SnippetManager.shared.expand(snippet: snippet, values: values)

        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(expanded, forType: .string)
        selfWriteChangeCount = pasteboard.changeCount

        SnippetManager.shared.incrementUseCount(for: snippet)

        SettingsModel.shared.pasteSound.play()
        dismissAndPaste()
    }

    // MARK: - Paste Stack

    /// Add an item to the paste stack (FIFO queue) — Pro only
    func addToPasteStack(_ item: ClipboardItem) {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.pasteStack, licenseService: ls)
            }
            return
        }
        pasteStack.append(item)
        SettingsModel.shared.pasteSound.play()
    }

    /// Paste the next item from the stack (FIFO or LIFO based on settings) — Pro only
    func pasteFromStack() {
        guard licenseService?.isPro == true else {
            if let ls = licenseService {
                ProUpsellWindow.show(feature: ProFeature.pasteStack, licenseService: ls)
            }
            return
        }
        guard !pasteStack.isEmpty else { return }
        let item: ClipboardItem = if SettingsModel.shared.pasteStackReversed {
            pasteStack.removeLast()
        } else {
            pasteStack.removeFirst()
        }
        paste(item: item)
    }

    /// Clear all items from the paste stack
    func clearPasteStack() {
        pasteStack.removeAll()
    }

    /// Dismiss the popover (so Cmd+V targets the correct app) then simulate paste.
    private func dismissAndPaste() {
        guard !isPasting else {
            logger.debug("Paste already in flight — skipping duplicate")
            return
        }
        isPasting = true
        NotificationCenter.default.post(name: .dismissForPaste, object: nil)
        #if APP_STORE
            showCopiedNotification()
            isPasting = false
        #else
            Task { @MainActor in
                try? await Task.sleep(for: .milliseconds(300))
                self.simulatePaste()
                self.isPasting = false
            }
        #endif
    }

    #if APP_STORE
        /// Show a brief "Copied to clipboard" notification for App Store builds
        /// where paste simulation (CGEvent) is not available in the sandbox.
        private func showCopiedNotification() {
            logger.debug("App Store mode: copied to clipboard, user must paste manually")
            // Request notification permission on first use, then deliver
            let center = UNUserNotificationCenter.current()
            center.requestAuthorization(options: [.alert, .sound]) { granted, _ in
                guard granted else { return }
                let content = UNMutableNotificationContent()
                content.title = "Copied to Clipboard"
                content.body = "Press \u{2318}V to paste"
                let request = UNNotificationRequest(
                    identifier: "com.saneclip.copied.\(UUID().uuidString)",
                    content: content,
                    trigger: nil
                )
                center.add(request)
            }
        }
    #else
        /// Whether accessibility permission alert is currently showing (prevents duplicates)
        private var isShowingPermissionAlert = false

        @discardableResult
        func triggerPasteFromExternalRequest() -> Bool {
            simulatePaste()
        }

        @discardableResult
        private func simulatePaste() -> Bool {
            guard isAccessibilityTrusted() else {
                logger.error("Accessibility permission not granted — paste blocked")
                guard !isShowingPermissionAlert else { return false }
                guard Self.shouldShowAccessibilityPrompt(
                    now: Date(),
                    suppressedUntil: suppressPermissionPromptUntil
                ) else {
                    logger.debug("Accessibility alert suppressed after manual fallback")
                    return false
                }
                isShowingPermissionAlert = true
                // Dispatch to escape the async Task context — runModal() needs its own run loop
                DispatchQueue.main.async { [weak self] in
                    guard let self else { return }
                    let action = self.showAccessibilityAlert()
                    self.handleAccessibilityAlertAction(action)
                    self.isShowingPermissionAlert = false
                }
                return false
            }

            guard let source = CGEventSource(stateID: .hidSystemState) else {
                logger.error("Failed to create CGEventSource for paste simulation")
                return false
            }

            guard let keyDown = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: true),
                  let keyUp = CGEvent(keyboardEventSource: source, virtualKey: 0x09, keyDown: false)
            else {
                logger.error("Failed to create CGEvent for paste simulation")
                return false
            }

            keyDown.flags = .maskCommand
            keyUp.flags = .maskCommand

            keyDown.post(tap: .cghidEventTap)
            keyUp.post(tap: .cghidEventTap)
            return true
        }

        private enum AccessibilityAlertAction {
            case openAccess
            case retry
            case manual
        }

        nonisolated static func shouldShowAccessibilityPrompt(now: Date, suppressedUntil: Date?) -> Bool {
            guard let suppressedUntil else { return true }
            return now >= suppressedUntil
        }

        private func isAccessibilityTrusted(promptSystemIfMissing: Bool = false) -> Bool {
            if promptSystemIfMissing {
                let options = [kAXTrustedCheckOptionPrompt.takeUnretainedValue() as String: true] as CFDictionary
                return AXIsProcessTrustedWithOptions(options)
            }
            return AXIsProcessTrusted()
        }

        private func openAccessibilitySettings() {
            if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security?Privacy_Accessibility") {
                NSWorkspace.shared.open(url)
            }
        }

        private func handleAccessibilityAlertAction(_ action: AccessibilityAlertAction) {
            switch action {
            case .openAccess:
                suppressPermissionPromptUntil = Date().addingTimeInterval(10)
                openAccessibilitySettings()
            case .retry:
                if isAccessibilityTrusted(promptSystemIfMissing: true) || isAccessibilityTrusted() {
                    _ = simulatePaste()
                } else {
                    suppressPermissionPromptUntil = Date().addingTimeInterval(5)
                }
            case .manual:
                suppressPermissionPromptUntil = Date().addingTimeInterval(permissionPromptCooldown)
            }
        }

        /// Show a standalone NSAlert for accessibility permission.
        /// Works even when the panel isn't visible (e.g. quick-paste hotkeys).
        private func showAccessibilityAlert() -> AccessibilityAlertAction {
            let alert = NSAlert()
            alert.messageText = Self.accessibilityAlertTitle
            alert.informativeText = Self.accessibilityAlertMessage
            alert.addButton(withTitle: Self.accessibilityOpenButtonTitle)
            alert.addButton(withTitle: Self.accessibilityRetryButtonTitle)
            alert.addButton(withTitle: Self.accessibilityManualButtonTitle)
            alert.alertStyle = .warning

            switch alert.runModal() {
            case .alertFirstButtonReturn:
                return .openAccess
            case .alertSecondButtonReturn:
                return .retry
            default:
                return .manual
            }
        }
    #endif

    func delete(item: ClipboardItem) {
        // Clean up thumbnail file if this is an image item
        if case .image = item.content {
            deleteThumbnail(id: item.id)
        }

        history.removeAll { $0.id == item.id }
        pinnedItems.removeAll { $0.id == item.id }
        saveHistory()

        #if ENABLE_SYNC
            SyncCoordinator.shared.queueDeleteForSync(itemID: item.id)
        #endif
    }

    // MARK: - Sync Support

    #if ENABLE_SYNC
        /// Insert an item received from iCloud sync (no re-sync trigger)
        func insertSyncedItem(_ item: ClipboardItem) {
            // Don't add duplicates
            guard !history.contains(where: { $0.id == item.id }) else { return }
            history.insert(item, at: 0)

            // Trim to max size, cleaning up thumbnails for removed items
            if history.count > maxHistorySize {
                let removed = history.suffix(from: maxHistorySize)
                for removedItem in removed {
                    if case .image = removedItem.content {
                        deleteThumbnail(id: removedItem.id)
                    }
                }
                history = Array(history.prefix(maxHistorySize))
            }

            saveHistory()
            logger.debug("Inserted synced item: \(item.id)")
        }

        /// Delete an item received from iCloud sync (no re-sync trigger)
        func deleteSyncedItem(_ itemID: UUID) {
            // Clean up thumbnail if it's an image item
            if let item = history.first(where: { $0.id == itemID }),
               case .image = item.content {
                deleteThumbnail(id: itemID)
            }
            history.removeAll { $0.id == itemID }
            pinnedItems.removeAll { $0.id == itemID }
            saveHistory()
            logger.debug("Deleted synced item: \(itemID)")
        }
    #endif

    func clearHistory() {
        // Clean up all thumbnail files
        for item in history {
            if case .image = item.content {
                deleteThumbnail(id: item.id)
            }
        }
        history.removeAll()
        saveHistory()
    }

    func pasteItemAt(index: Int) {
        guard index < history.count else { return }
        paste(item: history[index])
    }

    func togglePin(item: ClipboardItem) {
        if pinnedItems.contains(where: { $0.id == item.id }) {
            pinnedItems.removeAll { $0.id == item.id }
        } else {
            pinnedItems.insert(item, at: 0)
        }
        saveHistory()
    }

    /// Copy item to clipboard without triggering paste (Cmd+V)
    func copyWithoutPaste(item: ClipboardItem) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()

        switch item.content {
        case let .text(string):
            pasteboard.setString(string, forType: .string)
        case let .image(image):
            if let tiffData = image.tiffRepresentation {
                pasteboard.setData(tiffData, forType: .tiff)
            }
        }
        selfWriteChangeCount = pasteboard.changeCount

        SettingsModel.shared.pasteSound.play()

        logger.debug("Copied item to clipboard (no paste)")
    }

    /// Update an item's text content (for edit functionality)
    func updateItemContent(id: UUID, newContent: String) {
        guard !newContent.isEmpty else { return }

        if let index = history.firstIndex(where: { $0.id == id }) {
            let existing = history[index]
            let updatedItem = ClipboardItem(
                id: existing.id,
                content: .text(newContent),
                timestamp: existing.timestamp,
                sourceAppBundleID: existing.sourceAppBundleID,
                sourceAppName: existing.sourceAppName,
                pasteCount: existing.pasteCount,
                title: existing.title,
                tags: existing.tags,
                collection: existing.collection,
                note: existing.note
            )
            history[index] = updatedItem

            // Also update in pinnedItems if present
            if let pinnedIndex = pinnedItems.firstIndex(where: { $0.id == id }) {
                pinnedItems[pinnedIndex] = updatedItem
            }

            saveHistory()
            logger.debug("Updated content for item \(id)")
        }
    }

    /// Update an item's note
    func updateItemNote(id: UUID, note: String?) {
        let trimmedNote = note?.trimmingCharacters(in: .whitespacesAndNewlines)
        let finalNote = (trimmedNote?.isEmpty ?? true) ? nil : trimmedNote

        if let index = history.firstIndex(where: { $0.id == id }) {
            history[index].note = finalNote

            // Also update in pinnedItems if present
            if let pinnedIndex = pinnedItems.firstIndex(where: { $0.id == id }) {
                pinnedItems[pinnedIndex].note = finalNote
            }

            saveHistory()
            logger.debug("Updated note for item \(id)")
        }
    }

    func updateItemTitle(id: UUID, title: String?) {
        let trimmedTitle = title?.trimmingCharacters(in: .whitespacesAndNewlines)
        let finalTitle = (trimmedTitle?.isEmpty ?? true) ? nil : trimmedTitle

        if let index = history.firstIndex(where: { $0.id == id }) {
            history[index].title = finalTitle
            if let pinnedIndex = pinnedItems.firstIndex(where: { $0.id == id }) {
                pinnedItems[pinnedIndex].title = finalTitle
            }
            saveHistory()
            logger.debug("Updated title for item \(id)")
        }
    }

    func updateItemTags(id: UUID, tags: [String]) {
        let normalized = Array(
            Set(
                tags
                    .map { $0.trimmingCharacters(in: .whitespacesAndNewlines) }
                    .filter { !$0.isEmpty }
            )
        )
        .sorted()

        if let index = history.firstIndex(where: { $0.id == id }) {
            history[index].tags = normalized
            if let pinnedIndex = pinnedItems.firstIndex(where: { $0.id == id }) {
                pinnedItems[pinnedIndex].tags = normalized
            }
            saveHistory()
            logger.debug("Updated tags for item \(id)")
        }
    }

    func updateItemCollection(id: UUID, collection: String) {
        let trimmed = collection.trimmingCharacters(in: .whitespacesAndNewlines)
        let finalCollection = trimmed.isEmpty ? "Default" : trimmed

        if let index = history.firstIndex(where: { $0.id == id }) {
            history[index].collection = finalCollection
            if let pinnedIndex = pinnedItems.firstIndex(where: { $0.id == id }) {
                pinnedItems[pinnedIndex].collection = finalCollection
            }
            saveHistory()
            logger.debug("Updated collection for item \(id)")
        }
    }

    func availableCollections() -> [String] {
        let names = Set(history.map(\.collection).filter { !$0.isEmpty })
        let withDefault = names.union(["Default"])
        return withDefault.sorted()
    }

    @discardableResult
    func mergeItems(withIDs ids: [UUID], separator: String = "\n") -> ClipboardItem? {
        let textItems = ids.compactMap { id in
            history.first(where: { $0.id == id })
        }
        .compactMap { item -> ClipboardItem? in
            if case .text = item.content { return item }
            return nil
        }

        guard textItems.count >= 2 else { return nil }

        let mergedText = textItems.compactMap { item -> String? in
            if case let .text(text) = item.content { return text }
            return nil
        }
        .joined(separator: separator)

        let allTags = Array(Set(textItems.flatMap(\.tags))).sorted()
        let mergedItem = ClipboardItem(
            content: .text(mergedText),
            sourceAppBundleID: "com.saneclip.app",
            sourceAppName: "SaneClip",
            tags: allTags,
            collection: textItems.first?.collection ?? "Default",
            note: "Merged \(textItems.count) clips"
        )
        addItem(mergedItem)
        return mergedItem
    }

    func isPinned(_ item: ClipboardItem) -> Bool {
        pinnedItems.contains { $0.id == item.id }
    }

    /// Reorder pinned items via drag and drop
    func movePinnedItems(from source: IndexSet, to destination: Int) {
        pinnedItems.move(fromOffsets: source, toOffset: destination)
        saveHistory()
    }

    /// Export history to JSON data
    func exportHistory() -> Data? {
        let formatter = ISO8601DateFormatter()
        let pinnedIDs = Set(pinnedItems.map(\.id))
        let exportItems = history.compactMap { item -> [String: Any]? in
            var dict: [String: Any] = [
                "id": item.id.uuidString,
                "timestamp": formatter.string(from: item.timestamp),
                "pasteCount": item.pasteCount
            ]

            if case let .text(string) = item.content {
                dict["text"] = string
            } else {
                // Skip images in export
                return nil
            }

            if let bundleID = item.sourceAppBundleID {
                dict["sourceAppBundleID"] = bundleID
            }
            if let appName = item.sourceAppName {
                dict["sourceAppName"] = appName
            }
            if let title = item.title {
                dict["title"] = title
            }
            dict["tags"] = item.tags
            dict["collection"] = item.collection

            dict["isPinned"] = pinnedIDs.contains(item.id)

            return dict
        }

        return try? JSONSerialization.data(withJSONObject: exportItems, options: .prettyPrinted)
    }

    /// Static export function for use from Settings (reads from disk)
    nonisolated static func exportHistoryFromDisk() -> Data? {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let historyURL = appSupport
            .appendingPathComponent("SaneClip", isDirectory: true)
            .appendingPathComponent("history.json")

        guard FileManager.default.fileExists(atPath: historyURL.path),
              var data = try? Data(contentsOf: historyURL)
        else {
            return nil
        }

        // Auto-detect encrypted vs plaintext
        if HistoryEncryption.isEncrypted(data) {
            guard let decrypted = try? HistoryEncryption.decrypt(data) else { return nil }
            data = decrypted
        }

        guard let items = try? JSONDecoder().decode([SavedClipboardItem].self, from: data) else {
            return nil
        }

        let pinnedIDs = Set(UserDefaults.standard.stringArray(forKey: "pinnedItemIDs") ?? [])
        let formatter = ISO8601DateFormatter()

        let exportItems: [[String: Any]] = items.map { item in
            var dict: [String: Any] = [
                "id": item.id.uuidString,
                "timestamp": formatter.string(from: item.timestamp),
                "text": item.text,
                "pasteCount": item.pasteCount,
                "isPinned": pinnedIDs.contains(item.id.uuidString)
            ]
            if let bundleID = item.sourceAppBundleID {
                dict["sourceAppBundleID"] = bundleID
            }
            if let appName = item.sourceAppName {
                dict["sourceAppName"] = appName
            }
            if let title = item.title {
                dict["title"] = title
            }
            dict["tags"] = item.tags
            dict["collection"] = item.collection
            return dict
        }

        return try? JSONSerialization.data(withJSONObject: exportItems, options: .prettyPrinted)
    }

    // MARK: - Persistence

    private var historyFileURL: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let appFolder = appSupport.appendingPathComponent("SaneClip", isDirectory: true)
        try? FileManager.default.createDirectory(at: appFolder, withIntermediateDirectories: true)
        return appFolder.appendingPathComponent("history.json")
    }

    private var thumbnailsDirectory: URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
        let dir = appSupport
            .appendingPathComponent("SaneClip", isDirectory: true)
            .appendingPathComponent("thumbnails", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    /// Save a downsized thumbnail for an image item, returns the filename
    private func saveThumbnail(image: NSImage, id: UUID) -> String? {
        let maxDimension: CGFloat = 200
        let size = image.size

        // Calculate downsized dimensions preserving aspect ratio
        let scale: CGFloat = if size.width > maxDimension || size.height > maxDimension {
            min(maxDimension / size.width, maxDimension / size.height)
        } else {
            1.0
        }
        let newSize = NSSize(width: size.width * scale, height: size.height * scale)

        // Draw downsized image
        let resized = NSImage(size: newSize)
        resized.lockFocus()
        image.draw(in: NSRect(origin: .zero, size: newSize),
                   from: NSRect(origin: .zero, size: size),
                   operation: .copy,
                   fraction: 1.0)
        resized.unlockFocus()

        // Save as JPEG
        guard let tiffData = resized.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData),
              let jpegData = bitmap.representation(using: .jpeg, properties: [.compressionFactor: 0.7])
        else {
            logger.warning("Failed to create thumbnail JPEG for item \(id)")
            return nil
        }

        let filename = "\(id.uuidString).jpg"
        let fileURL = thumbnailsDirectory.appendingPathComponent(filename)
        do {
            try jpegData.write(to: fileURL, options: .atomic)
            return filename
        } catch {
            logger.warning("Failed to write thumbnail: \(error.localizedDescription)")
            return nil
        }
    }

    /// Delete the thumbnail file for a given item ID
    private func deleteThumbnail(id: UUID) {
        let fileURL = thumbnailsDirectory.appendingPathComponent("\(id.uuidString).jpg")
        try? FileManager.default.removeItem(at: fileURL)
    }

    /// Load a thumbnail image from disk
    private func loadThumbnail(filename: String) -> NSImage? {
        let fileURL = thumbnailsDirectory.appendingPathComponent(filename)
        return NSImage(contentsOf: fileURL)
    }

    func saveHistory() {
        // Save text items directly; save image items as downsized thumbnails on disk
        let savedItems = history.compactMap { item -> SavedClipboardItem? in
            switch item.content {
            case let .text(string):
                return SavedClipboardItem(
                    id: item.id,
                    text: string,
                    timestamp: item.timestamp,
                    sourceAppBundleID: item.sourceAppBundleID,
                    sourceAppName: item.sourceAppName,
                    pasteCount: item.pasteCount,
                    title: item.title,
                    tags: item.tags,
                    collection: item.collection,
                    note: item.note
                )
            case let .image(image):
                // Save thumbnail to disk; skip if save fails
                guard let filename = saveThumbnail(image: image, id: item.id) else { return nil }
                return SavedClipboardItem(
                    id: item.id,
                    text: "[Image]",
                    timestamp: item.timestamp,
                    sourceAppBundleID: item.sourceAppBundleID,
                    sourceAppName: item.sourceAppName,
                    pasteCount: item.pasteCount,
                    title: item.title,
                    tags: item.tags,
                    collection: item.collection,
                    note: item.note,
                    imageThumbnailFilename: filename
                )
            }
        }

        do {
            var data = try JSONEncoder().encode(savedItems)

            // Encrypt only when Pro is active and encryption is enabled.
            if licenseService?.isPro == true, SettingsModel.shared.encryptHistory {
                data = try HistoryEncryption.encrypt(data)
            }

            try data.write(to: historyFileURL, options: [.atomic, .completeFileProtection])

            // Save pinned item IDs separately
            let pinnedIDs = pinnedItems.map(\.id.uuidString)
            UserDefaults.standard.set(pinnedIDs, forKey: "pinnedItemIDs")

            // Update widget data
            updateWidgetData()
        } catch {
            logger.error("Failed to save history: \(error.localizedDescription)")
        }
    }

    // MARK: - Widget Support

    /// Updates widget data in the shared App Group container
    private func updateWidgetData() {
        // Convert history items to widget format
        let recentWidgetItems = history.prefix(10).map { item in
            WidgetClipboardItem(
                id: item.id,
                preview: item.preview,
                timestamp: item.timestamp,
                isPinned: isPinned(item),
                sourceAppName: item.sourceAppName,
                contentType: widgetContentType(for: item)
            )
        }

        // Convert pinned items to widget format
        let pinnedWidgetItems = pinnedItems.map { item in
            WidgetClipboardItem(
                id: item.id,
                preview: item.preview,
                timestamp: item.timestamp,
                isPinned: true,
                sourceAppName: item.sourceAppName,
                contentType: widgetContentType(for: item)
            )
        }

        let container = WidgetDataContainer(
            recentItems: Array(recentWidgetItems),
            pinnedItems: pinnedWidgetItems,
            lastUpdated: Date()
        )

        do {
            try container.save()
            // Tell WidgetKit to reload
            WidgetCenter.shared.reloadAllTimelines()
            logger.debug("Updated widget data with \(recentWidgetItems.count) recent, \(pinnedWidgetItems.count) pinned items")
        } catch {
            logger.warning("Failed to update widget data: \(error.localizedDescription)")
        }
    }

    private func widgetContentType(for item: ClipboardItem) -> WidgetClipboardItem.ContentType {
        switch item.content {
        case .text:
            if item.isURL { return .url }
            if item.isCode { return .code }
            return .text
        case .image:
            return .image
        }
    }

    private func loadHistory() {
        guard FileManager.default.fileExists(atPath: historyFileURL.path) else { return }

        do {
            var data = try Data(contentsOf: historyFileURL)

            // Auto-detect encrypted vs plaintext for seamless migration
            if HistoryEncryption.isEncrypted(data) {
                data = try HistoryEncryption.decrypt(data)
            }

            let items = try JSONDecoder().decode([SavedClipboardItem].self, from: data)
            history = items.compactMap { saved -> ClipboardItem? in
                let note = saved.note?.isEmpty == true ? nil : saved.note

                // Image item: load thumbnail from disk
                if let thumbnailFilename = saved.imageThumbnailFilename,
                   let image = loadThumbnail(filename: thumbnailFilename) {
                    return ClipboardItem(
                        id: saved.id,
                        content: .image(image),
                        timestamp: saved.timestamp,
                        sourceAppBundleID: saved.sourceAppBundleID,
                        sourceAppName: saved.sourceAppName,
                        pasteCount: saved.pasteCount,
                        title: saved.title,
                        tags: saved.tags,
                        collection: saved.collection,
                        note: note
                    )
                }

                // Skip image items whose thumbnail is missing (file deleted externally)
                if saved.imageThumbnailFilename != nil {
                    logger.warning("Thumbnail missing for item \(saved.id), skipping")
                    return nil
                }

                // Text item
                return ClipboardItem(
                    id: saved.id,
                    content: .text(saved.text),
                    timestamp: saved.timestamp,
                    sourceAppBundleID: saved.sourceAppBundleID,
                    sourceAppName: saved.sourceAppName,
                    pasteCount: saved.pasteCount,
                    title: saved.title,
                    tags: saved.tags,
                    collection: saved.collection,
                    note: note
                )
            }

            // Restore pinned items from saved IDs
            if let pinnedIDs = UserDefaults.standard.stringArray(forKey: "pinnedItemIDs") {
                let pinnedUUIDs = Set(pinnedIDs.compactMap { UUID(uuidString: $0) })
                pinnedItems = history.filter { pinnedUUIDs.contains($0.id) }
            }

            // If license service is already available, enforce tier limits immediately.
            enforceHistoryLimitIfNeeded()
        } catch {
            logger.error("Failed to load history: \(error.localizedDescription)")
        }
    }

    private func effectiveHistoryLimit() -> Int? {
        guard licenseService != nil else { return nil }
        return Self.historyLimit(maxHistorySize: maxHistorySize, isPro: licenseService?.isPro == true)
    }

    private func enforceHistoryLimitIfNeeded(saveAfterTrim: Bool = true) {
        guard let effectiveMax = effectiveHistoryLimit(), history.count > effectiveMax else { return }

        let removed = history.suffix(from: effectiveMax)
        for item in removed {
            if case .image = item.content {
                deleteThumbnail(id: item.id)
            }
        }

        history = Array(history.prefix(effectiveMax))
        pinnedItems = pinnedItems.filter { pinned in
            history.contains { $0.id == pinned.id }
        }

        if saveAfterTrim {
            saveHistory()
        }
    }

    // MARK: - Import History

    enum ImportError: Error, LocalizedError {
        case invalidFormat
        case readFailed
        case decodeFailed

        var errorDescription: String? {
            switch self {
            case .invalidFormat: "Invalid file format"
            case .readFailed: "Could not read file"
            case .decodeFailed: "Could not decode history data"
            }
        }
    }

    /// Import history from a JSON file
    /// - Parameters:
    ///   - url: URL to the JSON file
    ///   - merge: If true, merge with existing history; if false, replace entirely
    /// - Returns: Number of items imported
    @discardableResult
    func importHistory(from url: URL, merge: Bool) throws -> Int {
        // Read file
        guard let data = try? Data(contentsOf: url) else {
            throw ImportError.readFailed
        }

        // Try to decode as SavedClipboardItem array
        guard let items = try? JSONDecoder().decode([SavedClipboardItem].self, from: data) else {
            throw ImportError.decodeFailed
        }

        // Convert to ClipboardItems
        let importedItems = items.map { saved in
            ClipboardItem(
                id: saved.id,
                content: .text(saved.text),
                timestamp: saved.timestamp,
                sourceAppBundleID: saved.sourceAppBundleID,
                sourceAppName: saved.sourceAppName,
                pasteCount: saved.pasteCount,
                title: saved.title,
                tags: saved.tags,
                collection: saved.collection,
                note: saved.note?.isEmpty == true ? nil : saved.note
            )
        }

        if merge {
            // Skip items with existing IDs
            let existingIDs = Set(history.map(\.id))
            let newItems = importedItems.filter { !existingIDs.contains($0.id) }
            history.append(contentsOf: newItems)
            // Sort by timestamp, newest first
            history.sort { $0.timestamp > $1.timestamp }
            saveHistory()
            logger.info("Merged \(newItems.count) new items from import")
            return newItems.count
        } else {
            // Replace entire history
            history = importedItems
            pinnedItems = [] // Clear pins since items are new
            saveHistory()
            logger.info("Replaced history with \(importedItems.count) imported items")
            return importedItems.count
        }
    }

    // MARK: - Services Support

    /// Add an item from macOS Services (public wrapper for private addItem)
    func addItemFromService(_ item: ClipboardItem) {
        addItem(item)
    }

    // MARK: - PDF Export

    func exportItemAsPDF(item: ClipboardItem) {
        guard case let .text(text) = item.content else { return }

        let savePanel = NSSavePanel()
        savePanel.allowedContentTypes = [.pdf]
        let firstLine = text.components(separatedBy: .newlines).first ?? "clipboard"
        let cleanName = String(
            firstLine.prefix(50)
                .replacingOccurrences(of: "[^a-zA-Z0-9 _\\-]", with: "", options: .regularExpression)
                .trimmingCharacters(in: .whitespaces)
        )
        savePanel.nameFieldStringValue = (cleanName.isEmpty ? "clipboard" : cleanName) + ".pdf"

        guard savePanel.runModal() == .OK, let url = savePanel.url else { return }

        // PDF dimensions: US Letter
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 72
        let textRect = CGRect(x: margin, y: margin, width: pageWidth - 2 * margin, height: pageHeight - 2 * margin)

        let font = CTFontCreateWithName("Menlo" as CFString, 11, nil)
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.lineSpacing = 4
        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: NSColor.black,
            .paragraphStyle: paragraphStyle
        ]
        let attributedString = NSAttributedString(string: text, attributes: attributes)
        let framesetter = CTFramesetterCreateWithAttributedString(attributedString)

        var mediaBox = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        guard let dataConsumer = CGDataConsumer(url: url as CFURL),
              let pdfContext = CGContext(consumer: dataConsumer, mediaBox: &mediaBox, nil)
        else {
            logger.error("Failed to create PDF context")
            return
        }

        var currentIndex = 0
        while currentIndex < attributedString.length {
            pdfContext.beginPDFPage(nil)

            let path = CGPath(rect: textRect, transform: nil)
            let frameRange = CFRange(location: currentIndex, length: 0)
            let frame = CTFramesetterCreateFrame(framesetter, frameRange, path, nil)

            CTFrameDraw(frame, pdfContext)

            let visibleRange = CTFrameGetVisibleStringRange(frame)
            currentIndex += visibleRange.length

            pdfContext.endPDFPage()

            // Safety: break if no progress
            if visibleRange.length == 0 { break }
        }

        pdfContext.closePDF()
        logger.info("Exported clipboard item as PDF to \(url.path)")
    }
}
